# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComplexServicePbRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SubServicePbRequest_pb2 as SubServicePbRequest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ComplexServicePbRequest.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1d\x43omplexServicePbRequest.proto\x1a\x19SubServicePbRequest.proto\"Z\n\x17\x43omplexServicePbRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x13subServicePbRequest\x18\x02 \x01(\x0b\x32\x14.SubServicePbRequestB\\\n/com.alipay.rpc.common.service.facade.pb.requestP\x01Z\'com.alipay.rpc.common.service.facade.pbb\x06proto3')
  ,
  dependencies=[SubServicePbRequest__pb2.DESCRIPTOR,])




_COMPLEXSERVICEPBREQUEST = _descriptor.Descriptor(
  name='ComplexServicePbRequest',
  full_name='ComplexServicePbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ComplexServicePbRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subServicePbRequest', full_name='ComplexServicePbRequest.subServicePbRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=150,
)

_COMPLEXSERVICEPBREQUEST.fields_by_name['subServicePbRequest'].message_type = SubServicePbRequest__pb2._SUBSERVICEPBREQUEST
DESCRIPTOR.message_types_by_name['ComplexServicePbRequest'] = _COMPLEXSERVICEPBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComplexServicePbRequest = _reflection.GeneratedProtocolMessageType('ComplexServicePbRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXSERVICEPBREQUEST,
  __module__ = 'ComplexServicePbRequest_pb2'
  # @@protoc_insertion_point(class_scope:ComplexServicePbRequest)
  ))
_sym_db.RegisterMessage(ComplexServicePbRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n/com.alipay.rpc.common.service.facade.pb.requestP\001Z\'com.alipay.rpc.common.service.facade.pb'))
# @@protoc_insertion_point(module_scope)
