# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComplexServicePbResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SubServicePbResult_pb2 as SubServicePbResult__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ComplexServicePbResult.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1c\x43omplexServicePbResult.proto\x1a\x18SubServicePbResult.proto\"Y\n\x16\x43omplexServicePbResult\x12\x0e\n\x06result\x18\x01 \x01(\t\x12/\n\x12subServicePbResult\x18\x02 \x01(\x0b\x32\x13.SubServicePbResultB[\n.com.alipay.rpc.common.service.facade.pb.resultP\x01Z\'com.alipay.rpc.common.service.facade.pbb\x06proto3')
  ,
  dependencies=[SubServicePbResult__pb2.DESCRIPTOR,])




_COMPLEXSERVICEPBRESULT = _descriptor.Descriptor(
  name='ComplexServicePbResult',
  full_name='ComplexServicePbResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ComplexServicePbResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subServicePbResult', full_name='ComplexServicePbResult.subServicePbResult', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=147,
)

_COMPLEXSERVICEPBRESULT.fields_by_name['subServicePbResult'].message_type = SubServicePbResult__pb2._SUBSERVICEPBRESULT
DESCRIPTOR.message_types_by_name['ComplexServicePbResult'] = _COMPLEXSERVICEPBRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComplexServicePbResult = _reflection.GeneratedProtocolMessageType('ComplexServicePbResult', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXSERVICEPBRESULT,
  __module__ = 'ComplexServicePbResult_pb2'
  # @@protoc_insertion_point(class_scope:ComplexServicePbResult)
  ))
_sym_db.RegisterMessage(ComplexServicePbResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n.com.alipay.rpc.common.service.facade.pb.resultP\001Z\'com.alipay.rpc.common.service.facade.pb'))
# @@protoc_insertion_point(module_scope)
