# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SampleServicePbRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SampleServicePbRequest.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1cSampleServicePbRequest.proto\"&\n\x16SampleServicePbRequest\x12\x0c\n\x04name\x18\x01 \x01(\tB\\\n/com.alipay.rpc.common.service.facade.pb.requestP\x01Z\'com.alipay.rpc.common.service.facade.pbb\x06proto3')
)




_SAMPLESERVICEPBREQUEST = _descriptor.Descriptor(
  name='SampleServicePbRequest',
  full_name='SampleServicePbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SampleServicePbRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['SampleServicePbRequest'] = _SAMPLESERVICEPBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleServicePbRequest = _reflection.GeneratedProtocolMessageType('SampleServicePbRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLESERVICEPBREQUEST,
  __module__ = 'SampleServicePbRequest_pb2'
  # @@protoc_insertion_point(class_scope:SampleServicePbRequest)
  ))
_sym_db.RegisterMessage(SampleServicePbRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n/com.alipay.rpc.common.service.facade.pb.requestP\001Z\'com.alipay.rpc.common.service.facade.pb'))
# @@protoc_insertion_point(module_scope)
