# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubServicePbResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubServicePbResult.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18SubServicePbResult.proto\"\'\n\x12SubServicePbResult\x12\x11\n\tsubResult\x18\x01 \x01(\tB[\n.com.alipay.rpc.common.service.facade.pb.resultP\x01Z\'com.alipay.rpc.common.service.facade.pbb\x06proto3')
)




_SUBSERVICEPBRESULT = _descriptor.Descriptor(
  name='SubServicePbResult',
  full_name='SubServicePbResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subResult', full_name='SubServicePbResult.subResult', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['SubServicePbResult'] = _SUBSERVICEPBRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubServicePbResult = _reflection.GeneratedProtocolMessageType('SubServicePbResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBSERVICEPBRESULT,
  __module__ = 'SubServicePbResult_pb2'
  # @@protoc_insertion_point(class_scope:SubServicePbResult)
  ))
_sym_db.RegisterMessage(SubServicePbResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n.com.alipay.rpc.common.service.facade.pb.resultP\001Z\'com.alipay.rpc.common.service.facade.pb'))
# @@protoc_insertion_point(module_scope)
